### ISSUE TITLE
Operation Longbow neutral vehicles not spawning

### ISSUE THREAD

**Issue by alexgibbs606** [alexgibbs606/UnitedFrontEvents#1]
Vehicles marked for team neutral on the map are not spawning at start of round.

Discussion in Squad Modding Hub:
https://discord.com/channels/131516273048682496/131553429909798912/914674583498522715

**Comment by alexgibbs606** [comment]
https://discord.com/channels/131516273048682496/245614648978702346/812475290440957963

**Comment by alexgibbs606** [comment]
https://discord.com/channels/131516273048682496/245614648978702346/812217475973906473
https://discord.com/channels/131516273048682496/131553429909798912/918856702927970374

**Comment by poguepotamus** [comment]
LaughingJack's solution https://discord.com/channels/131516273048682496/245614648978702346/919490764071915540
